_target_: sn_gamestate.detection.yolo_multiclass_api.YOLOMulticlass
batch_size: 1
cfg:
  # Use any YOLO checkpoint with person and sports ball classes.
  path_to_checkpoint: yolov8n.pt
  min_confidence: 0.25
  class_map:
    person: player
    sports ball: ball
    goalkeeper: goalkeeper
